### ISSUE TITLE
There should be a link to the "Home" page of the wiki.

### ISSUE THREAD

**Issue by asynts** [codidact/docs#2]
There should be a link to the "Home" page in the sidebar, this screenshot should demonstrate what I mean:

![Screenshot from 2020-02-04 12-38-39](https://user-images.githubusercontent.com/31994781/73741852-6a507b00-474b-11ea-817d-a7a1929400a0.png)

I know that it's possible to expand the pages thing, but it's really annoying.

**Comment by luap42** [comment]
Resolved.

**Comment by asynts** [comment]
@luap42 How was this resolved?

**Comment by asynts** [comment]
Oh, I missed that.

Personally, the link should be at the very top, labeled "Home" or "Back", but this is okay too.
