### ISSUE TITLE
Missing image in scoring help

### ISSUE THREAD

**Issue by cellio** [codidact/docs#29]
https://meta.codidact.com/questions/279622

The help for [answer scoring](https://meta.codidact.com/help/scoring) is missing an image.  The file exists in the docs repo but has an uppercase PNG extension, while all the others have lowercase.  I suspect that the code in the qpixel repo is looking for lowercase.  Let's make it consistent here and then pick it up in the qpixel repo, unless @luap42 thinks we should handle it differently.

**Comment by sau226** [comment]
@cellio If this issue relates to PR #30 here and codidact/qpixel#336 in the qpixel repo, I think we can close this, unless you're waiting for the changes to go live on site:

**Comment by cellio** [comment]
Oh yeah, you're right.  We close issues when we fix them, and I collect them onto a list to go update status tags when the fixes actually get deployed.
