### ISSUE TITLE
Add help topic on how to claim imported content

### ISSUE THREAD

**Issue by cellio** [codidact/docs#32]
See https://github.com/codidact/qpixel/issues/335 in the qpixel repository.  We need to give users better guidance on how to claim their imported content, including a link on the stub user account for "is this you? if so, you can claim your content" where that's a link to this new help topic.

So first we need to write that topic.  There's existing content that can be mined, linked in the qpixel issue.

**Comment by superplane39** [comment]
Completed in https://github.com/codidact/docs/commit/0951f85731dc54412c2f1239e6560861c54d9fdf
