### ISSUE TITLE
Double standards for development team and user community due to the site's design

### ISSUE THREAD

**Issue by ShashankVM** [codidact/docs#33]
**Currently different standards are applied for the dev team and different standards for rest of the user community**
The dev team is allowed to bend and break the Code of Conduct of Codidact.com, while the rules are applied very strictly for the rest of the user community.

**To Reproduce**
1. Create a **community** account on meta.codidact.com 
2. Participate on 'meta.codidact.com' as a **non-staff user**
3. Question the staff user about their behaviour of breaking the Code of Conduct, such as creating off-topic posts.

**Expected behavior**
Get downvoted heavily and criticised disrespectfully, while your feedback is ignored and often deleted.

**Screenshots**
1. [What are the pros and cons of gamifying Codidact?](https://meta.codidact.com/posts/281238)
![Codidact Meta - What are the pros and cons of gamifying Codidac](https://user-images.githubusercontent.com/58113556/113391631-749ef100-93b1-11eb-87da-e3b87e64c276.png)
2.  [A note on April 1st](https://meta.codidact.com/posts/281235)
   ![Codidact Meta - A note on April 1st](https://user-images.githubusercontent.com/58113556/113391648-7bc5ff00-93b1-11eb-810b-551e795d00a8.png)

**Desktop:**
 - OS: All
 - Browser: All

**Smartphone:**
 - Device: All
 - OS: All
 - Browser: All
 
**Additional context**
This is a bug in the design of the Q&A Platform. I am not taking the risk of using the Meta Codidact site (or any Codidact site) anymore since I found this conversation:
>  @ShashankVM ah don't worry about security, everything is just client-side and it's just a small game. The secret code (often known as Konami cod and a common code for such easter eggs) is "Up Up Down Down Left Right Left Right A B Enter" (which are the keys you have to press).

>@luap42 Not quite. But anyone familiar with the code would know your mistake. It was the first code I tried yesterday, before
realizing I had to wait several hours. — mbomb007 about 15 hours ago

While the vulnerability is not revealed, I have reason to believe a vulnerability exists. I am not in a mood to find the vulnerability and *ethically* hack the site to prove my point.

----
I am afraid of using the Meta Codidact site after I got this comment which is unkind, made without research and made without **assuming good intent**:

@ShashankVM Your rep didn't decrease because you brought it up. Your rep decreased because you did so with the purpose of
creating a "stink" and complaining without reason, and everyone who downvoted wanted to do so. As the devs said, the Easter egg is opt-in. If you don't want to opt in, fine. Just stop making it such a big deal. — mbomb007 about 11 hours ago

For those with mobility impairments and those who [control the mouse using the keypad](https://www.youtube.com/watch?v=PVFRIz4aXcU), this "easter egg" might affect them in a very sad way. There are third party softwares that people use to control the mouse using keys. This "easter egg" might affect them.

One user says in a comment on the linked YouTube video:
> I'm one handed and apps like this save my life 

Has the development team thought of this?

I am not jealous of the development team for creating the "easter egg" and getting more reputation points (something the Codidact team itself created) for doing that. I am concerned about the **trustworthiness**, **integrity** and **software integrity** of the Codidact platform.

----
Quoting a staff user's comment:
> As far as "Easter Egg", I have always understood the term to refer to finding some special hidden "treat" - originating from the typical "Easter Egg Hunt", which as I understand it is an almost entirely secular event that was created at some time ago as a fun adjunct to the Christian holiday of Easter. As in, I don't think of Easter Egg as being any more "religious" than "fat Santa in a red suit with a sleigh and reindeer handing out gifts" - which is an image popularized by Coca Cola (among others) and commercialized, parodied, used as the basis of songs (many written by Jews...), etc. So for Easter Egg to have become a purely secular term for "hidden stuff inside web sites and video games" is not, to me, any problem at all. "Easter Egg" is "kosher" :-) — manassehkatz about 8 hours ago
One more digression: I enjoy when I find things such as "Easter Egg candy" that is actually Kosher (typically because everything in a particular factory is under Kosher supervision). — manassehkatz about 8 hours ago

- Easter eggs hunt as a fun event *adjunct* to the Christian holiday of Easter is okay, but creating an "easter egg"  to "celebrate" Fools' day is not okay in my opinion.
- So from the staff user's comment I can conclude that kosher and Kosher are two different terms, just like god and God are two different terms. I have observed that theists use the term "God" while atheists use "god". I have also observed that some religious people use "God" when referring to "their god" and "god' when referring to "other false gods".  I am a secular person too, but I don't enjoy it when cultures and religions are being made fun of by non-believers. Belief in the supernatural is not scientific by definition.

---

I have also noticed my answer to the post Number 2 "A note on April 1st" got **deleted** by the moderator. I flagged that question for being **off-topic** and that question did not get deleted, instead Monica Cellio added the "Announcement" tag. However, the "discussion" tag is still there, which means the "announcement" **should** still be open for discussion. The move of adding the "Announcement" tag to the question is like putting lipstick on a pig, since it does not solve the *real* problem of **the development team making announcements and taking decisions without asking the community for their opinions first**. 

The discussion going on Codidact Meta is not productive nor is it *fair*, since one party (the development team that believes they can have "easter eggs") has more muscle on Codidact Meta than the part of the community that objects to "easter eggs".

---

**Conclusion**:
- I am not going to participate in Meta Codidact or any codidact site anymore till this bug and the issues associated with it are fixed.
- If you have no plan to fix this bug, I request the site admin to delete my account.

**Comment by luap42** [comment]
Off topic for this repository. Use meta.codidact.com for community-level complains and requests.
